# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
    paths: ["Lab2/**"]
  pull_request:
    branches: [ "main" ]
    paths: ["Lab2/**"]

defaults:
  run:
    working-directory: Lab2
    

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: Lab2/package-lock.json
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run lint
    - run: npm test
    
  build-docker:
      name: Build and Push Docker Image
      runs-on: ubuntu-latest
      needs: lint-and-test
      steps:
        - uses: actions/checkout@v3
        - uses: docker/login-action@v2.1.0
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build and Push Docker Image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/node-test-sample:latest.
            docker push ${{ secrets.DOCKER_USERNAME }}/node-test-sample:latest
    
      
    
